spring.application.name=YouTubeTool

youtube.api.key=${YOUTUBE_API_KEY}
youtube.api.base.url=https://www.googleapis.com/youtube/v3
youtube.api.search.url=${youtube.api.base.url}/search
youtube.api.videos.url=${youtube.api.base.url}/videos

# Max number of related videos to fetch
youtube.api.max.related.videos=3

# ================================
# REDIS CONFIGURATION
# ================================
# "redis" here is the service name
# we will define in docker-compose.yml
# Docker automatically resolves this
# to the Redis container's IP address
spring.data.redis.host=redis
spring.data.redis.port=6379

# Cache TTL (Time To Live) = 1 hour
# After 1 hour, cached data expires
# and fresh API call will be made
spring.cache.redis.time-to-live=3600000